// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessLog is the predicate function for accesslog builders.
type AccessLog func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
